CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) DEFAULT 'some name' NOT NULL,
    role VARCHAR(255) DEFAULT 'USER' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

