// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package banner

import (
	"time"
)

type Banner struct {
	ID        int       `db:"id" json:"id"`
	FeatureID int       `db:"feature_id" json:"feature_id"`
	Title     string    `db:"title" json:"title"`
	Text      string    `db:"text" json:"text"`
	Url       string    `db:"url" json:"url"`
	IsActive  bool      `db:"is_active" json:"is_active"`
	IsDeleted bool      `db:"is_deleted" json:"is_deleted"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Tag struct {
	ID       int `db:"id" json:"id"`
	TagID    int `db:"tag_id" json:"tag_id"`
	BannerID int `db:"banner_id" json:"banner_id"`
}

type User struct {
	ID        int       `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Role      string    `db:"role" json:"role"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
